# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Calculadora
"""

#Aqui o usuário deve escolher a operação
operaçao = input('Digite a operação ( + , - , * , / ) ')

#Agora ele escolhe o primeiro e segundo número
num1 = int(input('Digite o primeiro número '))
num2 = int(input('Digite o segundo número '))

#A condicional para fazer as operações e mostrar na tela o resultado
if operaçao == '+':
  print('{} + {} = '.format(num1, num2))
  print(num1 + num2)

elif operaçao == '-':
  print('{} - {} = '.format(num1, num2))
  print(num1 - num2)

elif operaçao == '*':
  print('{} * {} = '.format(num1, num2))
  print(num1 * num2)

elif operaçao == '/':
  print('{} / {} = '.format(num1, num2))
  print(num1 / num2)

else:
  print('Operador inválido')